-- MySQL Script generated by MySQL Workbench
-- 10/28/16 19:23:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idPessoa` INT NOT NULL,
  `cpf` VARCHAR(8) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `telefoneResidencial` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fonteIndicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fonteIndicacao` (
  `idFonteIndicacao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFonteIndicacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL,
  `carteiraNit` VARCHAR(10) NOT NULL,
  `profissao` VARCHAR(45) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `idPessoa` INT NOT NULL,
  `idFonteIndicacao` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_pessoa1_idx` (`idPessoa` ASC),
  INDEX `fk_cliente_fonteIndicacao1_idx` (`idFonteIndicacao` ASC),
  CONSTRAINT `fk_cliente_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_fonteIndicacao1`
    FOREIGN KEY (`idFonteIndicacao`)
    REFERENCES `mydb`.`fonteIndicacao` (`idFonteIndicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idCargo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarioAdvogado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarioAdvogado` (
  `idFuncionarioAdvogado` INT NOT NULL,
  `carteiraOAB` VARCHAR(40) NOT NULL,
  `idCargo` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idFuncionarioAdvogado`),
  INDEX `fk_FuncionarioAdvogado_Cargo1_idx` (`idCargo` ASC),
  INDEX `fk_funcionarioAdvogado_pessoa1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_FuncionarioAdvogado_Cargo1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `mydb`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarioAdvogado_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comarca` (
  `idComarca` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`idComarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`natureza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`natureza` (
  `idNatureza` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNatureza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instancia` (
  `idInstancia` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstancia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vara` (
  `idVara` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVara`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`processo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`processo` (
  `idProcesso` INT NOT NULL,
  `numeroProcesso` VARCHAR(45) NOT NULL,
  `dataEntrada` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  `idFuncionarioAdvogado` INT NOT NULL,
  `idComarca` INT NOT NULL,
  `idNatureza` INT NOT NULL,
  `idInstancia` INT NOT NULL,
  `idVara` INT NOT NULL,
  PRIMARY KEY (`idProcesso`),
  INDEX `fk_processo_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_processo_funcionarioAdvogado1_idx` (`idFuncionarioAdvogado` ASC),
  INDEX `fk_processo_comarca1_idx` (`idComarca` ASC),
  INDEX `fk_processo_natureza1_idx` (`idNatureza` ASC),
  INDEX `fk_processo_instancia1_idx` (`idInstancia` ASC),
  INDEX `fk_processo_vara1_idx` (`idVara` ASC),
  CONSTRAINT `fk_processo_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_funcionarioAdvogado1`
    FOREIGN KEY (`idFuncionarioAdvogado`)
    REFERENCES `mydb`.`funcionarioAdvogado` (`idFuncionarioAdvogado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_comarca1`
    FOREIGN KEY (`idComarca`)
    REFERENCES `mydb`.`comarca` (`idComarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_natureza1`
    FOREIGN KEY (`idNatureza`)
    REFERENCES `mydb`.`natureza` (`idNatureza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_instancia1`
    FOREIGN KEY (`idInstancia`)
    REFERENCES `mydb`.`instancia` (`idInstancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_vara1`
    FOREIGN KEY (`idVara`)
    REFERENCES `mydb`.`vara` (`idVara`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `idDocumento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataEntrada` VARCHAR(10) NOT NULL,
  `pendencia` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  `idProcesso` INT NOT NULL,
  PRIMARY KEY (`idDocumento`),
  INDEX `fk_documento_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_documento_processo1_idx` (`idProcesso` ASC),
  CONSTRAINT `fk_documento_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_processo1`
    FOREIGN KEY (`idProcesso`)
    REFERENCES `mydb`.`processo` (`idProcesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
